### ISSUE TITLE
Move development dependencies to devDependencies

### ISSUE THREAD

**Issue by arnivuo** [d3plus/d3plus-common#58]
Hi,

Would it be possible to move dependencies that the end npm package user doesn't need to devDependencies. Now this package is forcing to install Electron (over 250 MB), Browserify, Babelify, ESLint, LiveServer, Faucet, Rollup, Tape, UglifyJS etc. for nothing.

Or is it that `d3plus-common` and `d3plus-text` should not be used via npm?

**Comment by davelandry** [comment]
@arnivuo good find. I'll make the switch.

**Comment by davelandry** [comment]
@arnivuo now that I've separated out the devDependencies, I'm having an issue using the bin scripts in other repos (like [d3plus-text](https://github.com/d3plus/d3plus-text)). You'll notice that the "test" script in that repo uses d3plus-common's `d3plus-test` script, and when that runs, it gets an error because one of the devDependencies is not installed.

I think we need to move towards having to `npm i -g d3plus-common` when developing, which I'm ok with, but I still can't get that test script to work in a different repo. Any thoughts?

**Comment by davelandry** [comment]
@arnivuo after some thought, I'm going to be separating our the scripts to separate dev repo.

**Comment by arnivuo** [comment]
Hi, sorry missed your comment.

I noticed issue with bin scripts but didn't have any good idea how deal with those. That separate dev repo sounds good.
